apiVersion: v1
kind: Secret
metadata:
  labels:
    app: app
  name: app-secret
type: Opaque
stringData:
  APP_KEY: "base64:gUOOhq/odpN93S5S7/+4w0xPvDkuvh2TTI+7QTPn+jI="
  DB_PASSWORD: "root"
  MAIL_USERNAME: "79e0bba495b675"
  MAIL_PASSWORD: "ac57c470bf2d3f"
