apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - app-env-configmap.yaml
  - app-secret.yaml
  - app-hpa.yaml
  - nginx-hpa.yaml

patches:
  - path: app-env-patch.yaml
    target:
      kind: Deployment
      name: app
