services:
  app:
    container_name: app
    build:
      args:
        user: asif
        uid: 1412
      context: .
      dockerfile: /docker/php-fpm/Dockerfile
      target: production
    volumes:
      - app_supervisor_logs:/var/www/storage/logs/supervisor
    expose:
      - "9000"
    environment:
      - APP_ENV=production
    working_dir: /var/www/
    restart: unless-stopped

  nginx:
      container_name: nginx
      build:
        context: .
        dockerfile: ./docker/nginx/Dockerfile
        target: production
      environment:
        - NGINX_HOST=app
        - NGINX_PORT=9000
      ports:
        - "8000:80"
      depends_on:
        - app  
      restart: unless-stopped

volumes:
    app_supervisor_logs: