apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/local/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/local/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - env:
            - name: NGINX_HOST
              value: app
            - name: NGINX_PORT
              value: "9000"
          image: passport_token_auth-nginx:latest
          imagePullPolicy: IfNotPresent
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
