apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-deployment.yaml
  - app-service.yaml
  - app-supervisor-logs-pvc.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - mysql-data-pvc.yaml
  - gateway.yaml
  - nginx-httproute.yaml
