apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-mysql
        - name: run-migrations
          volumeMounts:
            - mountPath: /var/www/.env
              name: app-env
              subPath: .env
      containers:
        - name: app
          env:
            - name: APP_ENV
              value: staging
          volumeMounts:
            - mountPath: /var/www/.env
              name: app-env
              subPath: .env
      volumes:
        - name: app-env
          configMap:
            name: app-env
            items:
              - key: .env.staging
                path: .env
