apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - app-env-configmap.yaml
  - app-secret.yaml
  - app-hpa.yaml
  # - nginx-hpa.yaml

images:
  - name: passport_token_auth-app
    newName: passport_token_auth-app
    newTag: staging
  - name: passport_token_auth-nginx
    newName: passport_token_auth-nginx
    newTag: staging

patches:
  - path: app-env-patch.yaml
    target:
      kind: Deployment
      name: app
  - path: httproute-patch.yaml
    target:
      kind: HTTPRoute
      name: nginx
